// src/index.ts
// Note: Env type is generated by `wrangler types` in worker-configuration.d.ts
import type { MigrationStep } from './types';
import { GUIDE_CATEGORIES, getGuideBySlug } from './guides';
import { ZERO_DOWNTIME_MIGRATION_STEPS } from './guides/application-services/zero-downtime-migration';
import { SASE_ONBOARDING_STEPS } from './guides/cloudflare-one/sase-onboarding';

// Map of guide slugs to their step data
const GUIDE_STEPS: Record<string, Omit<MigrationStep, 'status'>[]> = {
	'zero-downtime-migration': ZERO_DOWNTIME_MIGRATION_STEPS,
	'sase-onboarding': SASE_ONBOARDING_STEPS,
};

// Response headers for JSON API endpoints
const JSON_HEADERS: HeadersInit = {
	'Content-Type': 'application/json',
	'Access-Control-Allow-Origin': '*',
	'Access-Control-Allow-Methods': 'GET, OPTIONS',
	'Access-Control-Allow-Headers': 'Content-Type',
};

export default {
	async fetch(request: Request, env: Env): Promise<Response> {
		const url = new URL(request.url);

		// Handle CORS preflight
		if (request.method === 'OPTIONS') {
			return new Response(null, { headers: JSON_HEADERS });
		}

		// API endpoints
		if (url.pathname.startsWith('/api/')) {
			return handleApiRequest(url, request);
		}

		// Route: Guide pages - serve guide.html for available guides
		if (url.pathname.startsWith('/guide/')) {
			const guideSlug = url.pathname.replace('/guide/', '').replace(/\/$/, '');
			const guide = getGuideBySlug(guideSlug);

			if (guide && guide.status === 'available') {
				// Rewrite URL to serve guide.html using assets binding
				return env.ASSETS.fetch(new URL('/guide.html', request.url));
			}

			return Response.json(
				{ error: 'Guide not found' },
				{ status: 404, headers: JSON_HEADERS }
			);
		}

		// Serve static assets (index.html is landing page at root)
		// Terraform files in /terraform/ are served directly as static assets
		return env.ASSETS.fetch(request);
	},
} satisfies ExportedHandler<Env>;

function handleApiRequest(url: URL, request: Request): Response {
	// Only allow GET requests for API endpoints
	if (request.method !== 'GET') {
		return Response.json(
			{ error: 'Method not allowed' },
			{ status: 405, headers: JSON_HEADERS }
		);
	}

	// GET /api/steps - return migration steps (default: zero-downtime-migration)
	if (url.pathname === '/api/steps') {
		const steps: MigrationStep[] = ZERO_DOWNTIME_MIGRATION_STEPS.map((step) => ({
			...step,
			status: 'pending',
		}));
		return Response.json({ steps }, { headers: JSON_HEADERS });
	}

	// GET /api/steps/:slug - return steps for a specific guide
	const stepsMatch = url.pathname.match(/^\/api\/steps\/([a-z0-9-]+)$/);
	if (stepsMatch) {
		const guideSteps = GUIDE_STEPS[stepsMatch[1]];
		if (guideSteps) {
			const steps: MigrationStep[] = guideSteps.map((step) => ({
				...step,
				status: 'pending',
			}));
			return Response.json({ steps }, { headers: JSON_HEADERS });
		}
		return Response.json(
			{ error: 'Guide steps not found' },
			{ status: 404, headers: JSON_HEADERS }
		);
	}

	// GET /api/guides - return guides registry
	if (url.pathname === '/api/guides') {
		return Response.json({ categories: GUIDE_CATEGORIES }, { headers: JSON_HEADERS });
	}

	// GET /api/guides/:slug - return specific guide metadata
	const guideMatch = url.pathname.match(/^\/api\/guides\/([a-z0-9-]+)$/);
	if (guideMatch) {
		const guide = getGuideBySlug(guideMatch[1]);
		if (guide) {
			return Response.json(guide, { headers: JSON_HEADERS });
		}
		return Response.json(
			{ error: 'Guide not found' },
			{ status: 404, headers: JSON_HEADERS }
		);
	}

	// GET /api/documentation - return documentation links
	if (url.pathname === '/api/documentation') {
		const documentation = {
			general: [
				'https://developers.cloudflare.com/fundamentals/performance/minimize-downtime/',
				'https://developers.cloudflare.com/fundamentals/concepts/how-cloudflare-works/',
			],
			partial_setup: ['https://developers.cloudflare.com/dns/zone-setups/partial-setup/setup/'],
			full_setup: ['https://developers.cloudflare.com/dns/zone-setups/full-setup/setup/'],
			conversion: ['https://developers.cloudflare.com/dns/zone-setups/conversions/convert-partial-to-full/'],
			ssl: [
				'https://developers.cloudflare.com/ssl/edge-certificates/advanced-certificate-manager/',
				'https://developers.cloudflare.com/ssl/edge-certificates/changing-dcv-method/methods/txt/',
			],
			dnssec: [
				'https://developers.cloudflare.com/dns/dnssec/dnssec-active-migration/',
				'https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/',
			],
			proxy: ['https://developers.cloudflare.com/dns/proxy-status/'],
		};
		return Response.json(documentation, { headers: JSON_HEADERS });
	}

	return Response.json(
		{ error: 'Not found' },
		{ status: 404, headers: JSON_HEADERS }
	);
}
